### ISSUE TITLE
[Enhancements]  Provide one card per anime instead of per episode.

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#54] opened 2023-08-14 04:27 UTC
![Screenshot (35)](https://github.com/Ani-Moopa/Moopa/assets/142195419/1de1dec1-ae24-4b62-acb5-b4bc2e8ccc42)
![Screenshot (34)](https://github.com/Ani-Moopa/Moopa/assets/142195419/6721ba6d-75b4-4e37-ba56-543876b2abb6)
  
# Describe the bug
each time I watch anima and when I go to home screen they will showing over there but when I watch the same anime in new episode i have to delete it and episode I watched he's dead showing every episode one by one watched can you change that.I will put a screenshot between this website and other website

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Possible Solution**
-

**Comment by DevanAbinaya** [comment] 2023-08-14 04:34
hi, I hope I get this correctly, so you want it to return a single card for each anime instead of each episodes?

**Comment by pookiewx** [comment] 2023-08-14 04:35
yes

**Comment by DevanAbinaya** [comment] 2023-08-14 04:41
okay got it, I'll see what I can do about it, thanks for the suggestion :)

**Comment by DevanAbinaya** [comment] 2023-08-14 04:44
do not close this issue until your problem solved, thanks

**Comment by pookiewx** [comment] 2023-08-14 05:20
so how long you take to fix this kind of problem

**Comment by chitrakshbotwala** [comment] 2023-08-14 05:23
It would take some time bruda as we are working on watch together feature and a lot of other bug fixes right now , we need some time to fix it , I gurantee you it wouldn't take much time just have some patience 😊

**Comment by pookiewx** [comment] 2023-08-14 05:27
I don't care how much time it takes because I like this website so much

**Comment by DevanAbinaya** [comment] 2023-08-14 05:31
> so how long you take to fix this kind of problem

implementing this feature usually wouldn't take that long, but I don't want it to have more issue when it's deployed to production so it can take some time for me to make sure it's ready for production

**Comment by pookiewx** [comment] 2023-08-14 05:37
ok

**Comment by pookiewx** [comment] 2023-08-14 06:36
I am just wondering how many people are using this website

**Comment by DevanAbinaya** [comment] 2023-08-14 06:47
I can't tell you for sure, but as cloudflare says we got like 1k unique visitors per day.

If you have any questions or discussion to ask, please join our [discord server](https://discord.gg/v5fjSdKwr2) or open a [discussion](https://github.com/Ani-Moopa/Moopa/discussions) chat on github since this place isn't meant for chatting, thank you.

**Comment by pookiewx** [comment] 2023-08-17 00:42
If you Don't mind if I ask You are almost done with the problem You start working on it.

**Comment by DevanAbinaya** [comment] 2023-08-17 05:06
I've updated the site, now recently watched only shows one episode per show, additionally I've added play next episode button to it if next episode is available, also on more recently watched page would still showing all episodes it's intentional not a bug. Thank you for the wait, I'm closing this issue.

**Closed by DevanAbinaya** 2023-08-17 05:06 UTC
Labels: 🐛 bug, enhancement

**Comment by pookiewx** [comment] 2023-08-17 06:09
Thanks
